import smartpy as sp

class Fa2ErrorMessage:
    def token_undefined():        return "FA2_TOKEN_UNDEFINED"
    def not_operator():           return "FA2_NOT_OPERATOR"
    def not_owner():              return "FA2_NOT_OWNER"
    def insufficient_balance():   return "FA2_INSUFFICIENT_BALANCE"


class ErrorMessage:
    def unauthorized_user():         return "ANGRY_TEENAGERS_UNAUTHORISED_USER"
    def paused():                    return "ANGRY_TEENAGERS_PAUSED"
    def not_admin():                 return "ANGRY_TEENAGERS_NOT_ADMIN"
    def no_next_admin():             return "ANGRY_TEENAGERS_NO_NEXT_ADMIN"
    def no_land_available():         return "ANGRY_TEENAGERS_NO_LAND_AVAILABLE"
    def balance_inconsistency():     return "ANGRY_TEENAGERS_BALANCE_INCONSISTENCY"
    def sale_event_already_open():   return "ANGRY_TEENAGERS_SALE_EVENT_ALREADY_OPEN"
    def sale_no_event_open():        return "ANGRY_TEENAGERS_SALE_NO_EVENT_OPEN"
    def sale_invalid_deadline():     return "ANGRY_TEENAGERS_SALE_INVALID_DEADLINE"
    def forbidden_operation():       return "ANGRY_TEENAGERS_FORBIDDEN_OPERATION"
    def invalid_parameter():         return "ANGRY_TEENAGERS_INVALID_PARAMETER"
    def sale_no_space_remaining():   return "ANGRY_TEENAGERS_NO_SPACE_REMAINING"
    def sale_no_token():             return "ANGRY_TEENAGERS_NO_TOKEN"
    def invalid_amount():            return "ANGRY_TEENAGERS_INVALID_AMOUNT"
    def dao_vote_in_progress():      return "ANGRY_TEENAGERS_DAO_VOTE_IN_PROGRESS"
    def dao_only_for_dao():          return "ANGRY_TEENAGERS_DAO_ONLY_FOR_DAO"
    def dao_already_registered():    return "ANGRY_TEENAGERS_DAO_ALREADY_REGISTERED"
    def dao_not_registered():        return "ANGRY_TEENAGERS_DAO_NOT_REGISTERED"
    def dao_invalid_voting_strat():  return "ANGRY_TEENAGERS_DAO_INVALID_VOTING_STRAT"
    def dao_invalid_token_view():    return "ANGRY_TEENAGERS_DAO_INVALID_TOKEN_VIEW"
    def dao_no_voting_power():       return "ANGRY_TEENAGERS_DAO_NO_VOTING_POWER"
    def dao_no_vote_open():          return "ANGRY_TEENAGERS_DAO_NO_VOTE_OPEN"
    def dao_no_poll_descriptor():    return "ANGRY_TEENAGERS_DAO_NO_POLL_DESCRIPTOR"
    def dao_poll_descriptor_defined(): return "ANGRY_TEENAGERS_DAO_POLL_DESCRIPTOR_DEFINED"
    def dao_vote_not_yet_open():     return "ANGRY_TEENAGERS_DAO_VOTE_NOT_YET_OPEN"
    def dao_vote_period_is_over():      return "ANGRY_TEENAGERS_DAO_VOTE_PERIOD_IS_OVER"
    def dao_no_invalid_proposal():   return "ANGRY_TEENAGERS_DAO_INVALID_PROPOSAL"
    def dao_invalid_outcome_id():    return "ANGRY_TEENAGERS_DAO_INVALID_OUTCOME_ID"
    def dao_vote_already_received(): return "ANGRY_TEENAGERS_DAO_VOTE_ALREADY_RECEIVED"
    def dao_invalid_vote_id():       return "ANGRY_TEENAGERS_DAO_INVALID_VOTE_ID"
    def dao_invalid_vote_value():    return "ANGRY_TEENAGERS_DAO_INVALID_VOTE_VALUE"
    def invalid_token_metadata():    return "ANGRY_TEENAGERS_INVALID_TOKEN_METADATA"
    def token_revealed():            return "ANGRY_TEENAGERS_TOKEN_REVEALED"
